import Head from "next/head";
import tw from "tailwind-styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>Auei</Container>
    </>
  );
}

interface ContainerProps {
  full?: boolean;
}

const Container = tw.main<ContainerProps>`
  ${(props) => (props.full ? "px-5" : "w-3/4 m-auto")}
  py-5
`;
